// toast() 메시지 맨 앞에 하드코딩으로 박혀 있던 일반 알림 이모지(⚠️✨💀📜...) →
// 대표 도트 배지 매핑. event-icons.js(사건 종류 14개)와 같은 방식이지만,
// 이쪽은 "특정 사건"이 아니라 그냥 범용 알림/상태 표시용 이모지다.
// toast()가 msg 맨 앞의 이모지를 자동 인식해서 이 표에 있으면 이미지로
// 바꿔 보여준다(utils.js의 toast() 참고) — 호출부 694곳을 일일이 고칠
// 필요 없이 한 곳에서 전부 커버된다.
const COMMON_EMOJI_ICONS = [
  { emoji: "⚠️", id: "ico-0", rarity: "uncommon" }, // 58회
  { emoji: "✨", id: "ico-1", rarity: "uncommon" }, // 35회
  { emoji: "💰", id: "ico-2", rarity: "uncommon" }, // 25회
  { emoji: "🔓", id: "ico-3", rarity: "uncommon" }, // 23회
  { emoji: "🎁", id: "ico-4", rarity: "common" }, // 16회
  { emoji: "🏆", id: "ico-5", rarity: "common" }, // 16회
  { emoji: "❌", id: "ico-6", rarity: "common" }, // 15회
  { emoji: "✅", id: "ico-7", rarity: "common" }, // 14회
  { emoji: "🌑", id: "ico-8", rarity: "common" }, // 11회
  { emoji: "💔", id: "ico-9", rarity: "common" }, // 11회
  { emoji: "📋", id: "ico-10", rarity: "common" }, // 11회
  { emoji: "🩸", id: "ico-11", rarity: "common" }, // 10회
  { emoji: "🏴", id: "ico-12", rarity: "common" }, // 9회
  { emoji: "📦", id: "ico-13", rarity: "common" }, // 9회
  { emoji: "🗺️", id: "ico-14", rarity: "common" }, // 9회
  { emoji: "⛓️", id: "ico-15", rarity: "common" }, // 8회
  { emoji: "🔨", id: "ico-16", rarity: "common" }, // 8회
  { emoji: "💸", id: "ico-17", rarity: "common" }, // 7회
  { emoji: "🛡️", id: "ico-18", rarity: "common" }, // 7회
  { emoji: "💬", id: "ico-19", rarity: "common" }, // 7회
  { emoji: "📖", id: "ico-20", rarity: "common" }, // 7회
  { emoji: "📈", id: "ico-21", rarity: "common" }, // 7회
  { emoji: "🩹", id: "ico-22", rarity: "common" }, // 6회
  { emoji: "🌋", id: "ico-23", rarity: "common" }, // 6회
  { emoji: "🎯", id: "ico-24", rarity: "common" }, // 6회
  { emoji: "⏳", id: "ico-25", rarity: "common" }, // 6회
  { emoji: "🐺", id: "ico-26", rarity: "common" }, // 6회
  { emoji: "⬆️", id: "ico-27", rarity: "common" }, // 5회
  { emoji: "🔒", id: "ico-28", rarity: "common" }, // 5회
  { emoji: "🌍", id: "ico-29", rarity: "common" }, // 5회
  { emoji: "🔍", id: "ico-30", rarity: "common" }, // 5회
  { emoji: "👻", id: "ico-31", rarity: "common" }, // 5회
  { emoji: "🌟", id: "ico-32", rarity: "common" }, // 5회
  { emoji: "🎉", id: "ico-33", rarity: "common" }, // 5회
  { emoji: "👑", id: "ico-34", rarity: "common" }, // 4회
  { emoji: "📉", id: "ico-35", rarity: "common" }, // 4회
  { emoji: "💡", id: "ico-36", rarity: "common" }, // 4회
  { emoji: "💎", id: "ico-37", rarity: "common" }, // 4회
  { emoji: "⚗️", id: "ico-38", rarity: "common" }, // 4회
  { emoji: "📍", id: "ico-39", rarity: "common" }, // 4회
  { emoji: "⚓", id: "ico-40", rarity: "common" }, // 4회
  { emoji: "👁️", id: "ico-41", rarity: "common" }, // 4회
  { emoji: "🌀", id: "ico-42", rarity: "common" }, // 4회
  { emoji: "🎭", id: "ico-43", rarity: "common" }, // 4회
  { emoji: "📢", id: "ico-44", rarity: "common" }, // 4회
  { emoji: "⚒️", id: "ico-45", rarity: "common" }, // 4회
  { emoji: "🗝️", id: "ico-46", rarity: "common" }, // 4회
  { emoji: "🕶️", id: "ico-47", rarity: "common" }, // 3회
  { emoji: "🕯️", id: "ico-48", rarity: "common" }, // 3회
  { emoji: "👥", id: "ico-49", rarity: "common" }, // 3회
  { emoji: "🏪", id: "ico-50", rarity: "common" }, // 3회
  { emoji: "🎼", id: "ico-51", rarity: "common" }, // 3회
  { emoji: "☠️", id: "ico-52", rarity: "common" }, // 3회
  { emoji: "💨", id: "ico-53", rarity: "common" }, // 3회
  { emoji: "💚", id: "ico-54", rarity: "common" }, // 3회
  { emoji: "🎲", id: "ico-55", rarity: "common" }, // 3회
  { emoji: "🎪", id: "ico-56", rarity: "common" }, // 3회
  { emoji: "😤", id: "ico-57", rarity: "common" }, // 3회
  { emoji: "💛", id: "ico-58", rarity: "common" }, // 3회
  { emoji: "🔮", id: "ico-59", rarity: "common" }, // 3회
  { emoji: "🧬", id: "ico-60", rarity: "common" }, // 3회
  { emoji: "🏰", id: "ico-61", rarity: "common" }, // 3회
  { emoji: "🧝", id: "ico-62", rarity: "common" }, // 3회
  { emoji: "🗡️", id: "ico-63", rarity: "common" }, // 2회
  { emoji: "⏪", id: "ico-64", rarity: "common" }, // 2회
  { emoji: "🚪", id: "ico-65", rarity: "common" }, // 2회
  { emoji: "🐾", id: "ico-66", rarity: "common" }, // 2회
  { emoji: "🌊", id: "ico-67", rarity: "common" }, // 2회
  { emoji: "👤", id: "ico-68", rarity: "common" }, // 2회
  { emoji: "🏕️", id: "ico-69", rarity: "common" }, // 2회
  { emoji: "⚱️", id: "ico-70", rarity: "common" }, // 2회
  { emoji: "🔧", id: "ico-71", rarity: "common" }, // 2회
  { emoji: "📗", id: "ico-72", rarity: "common" }, // 2회
  { emoji: "🕵️", id: "ico-73", rarity: "common" }, // 2회
  { emoji: "🌱", id: "ico-74", rarity: "common" }, // 2회
  { emoji: "☀️", id: "ico-75", rarity: "common" }, // 2회
  { emoji: "🎓", id: "ico-76", rarity: "common" }, // 2회
  { emoji: "🏚️", id: "ico-77", rarity: "common" }, // 2회
  { emoji: "🖤", id: "ico-78", rarity: "common" }, // 2회
  { emoji: "⚙️", id: "ico-79", rarity: "common" }, // 2회
  { emoji: "🫂", id: "ico-80", rarity: "common" }, // 2회
  { emoji: "🌕", id: "ico-81", rarity: "common" }, // 2회
  { emoji: "⚜️", id: "ico-82", rarity: "common" }, // 2회
  { emoji: "💗", id: "ico-83", rarity: "common" }, // 2회
  { emoji: "🌾", id: "ico-84", rarity: "common" }, // 2회
  { emoji: "➡️", id: "ico-85", rarity: "common" }, // 1회
  { emoji: "👋", id: "ico-86", rarity: "common" }, // 1회
  { emoji: "🕰️", id: "ico-87", rarity: "common" }, // 1회
  { emoji: "😌", id: "ico-88", rarity: "common" }, // 1회
  { emoji: "🎻", id: "ico-89", rarity: "common" }, // 1회
  { emoji: "🦴", id: "ico-90", rarity: "common" }, // 1회
  { emoji: "🐫", id: "ico-91", rarity: "common" }, // 1회
  { emoji: "🚶", id: "ico-92", rarity: "common" }, // 1회
  { emoji: "🚢", id: "ico-93", rarity: "common" }, // 1회
  { emoji: "⛵", id: "ico-94", rarity: "common" }, // 1회
  { emoji: "⛈️", id: "ico-95", rarity: "common" }, // 1회
  { emoji: "⛴️", id: "ico-96", rarity: "common" }, // 1회
  { emoji: "🐙", id: "ico-97", rarity: "common" }, // 1회
  { emoji: "🏝️", id: "ico-98", rarity: "common" }, // 1회
  { emoji: "🏦", id: "ico-99", rarity: "common" }, // 1회
  { emoji: "🔗", id: "ico-100", rarity: "common" }, // 1회
  { emoji: "⚠", id: "ico-101", rarity: "common" }, // 1회
  { emoji: "🛏️", id: "ico-102", rarity: "common" }, // 1회
  { emoji: "⛩️", id: "ico-103", rarity: "common" }, // 1회
  { emoji: "🏛️", id: "ico-104", rarity: "common" }, // 1회
  { emoji: "😐", id: "ico-105", rarity: "common" }, // 1회
  { emoji: "🏁", id: "ico-106", rarity: "common" }, // 1회
  { emoji: "↔", id: "ico-107", rarity: "common" }, // 1회
  { emoji: "🏬", id: "ico-108", rarity: "common" }, // 1회
  { emoji: "🚨", id: "ico-109", rarity: "common" }, // 1회
  { emoji: "🎒", id: "ico-110", rarity: "common" }, // 1회
  { emoji: "⏰", id: "ico-111", rarity: "common" }, // 1회
  { emoji: "⚕️", id: "ico-112", rarity: "common" }, // 1회
  { emoji: "🎩", id: "ico-113", rarity: "common" }, // 1회
  { emoji: "⭐", id: "ico-114", rarity: "common" }, // 1회
  { emoji: "💝", id: "ico-115", rarity: "common" }, // 1회
  { emoji: "📸", id: "ico-116", rarity: "common" }, // 1회
  { emoji: "🗓️", id: "ico-117", rarity: "common" }, // 1회
  { emoji: "😈", id: "ico-118", rarity: "common" }, // 1회
  { emoji: "😱", id: "ico-119", rarity: "common" }, // 1회
  { emoji: "⚖️", id: "ico-120", rarity: "common" }, // 1회
  { emoji: "🎖️", id: "ico-121", rarity: "common" }, // 1회
  { emoji: "🏺", id: "ico-122", rarity: "common" }, // 1회
  { emoji: "🔄", id: "ico-123", rarity: "common" }, // 1회
  { emoji: "🧠", id: "ico-124", rarity: "common" }, // 1회
  { emoji: "🎬", id: "ico-125", rarity: "common" }, // 1회
  { emoji: "👹", id: "ico-126", rarity: "common" }, // 1회
  { emoji: "🧩", id: "ico-127", rarity: "common" }, // 1회
  { emoji: "🏷️", id: "ico-128", rarity: "common" }, // 1회
  { emoji: "😢", id: "ico-129", rarity: "common" }, // 1회
  { emoji: "✏️", id: "ico-130", rarity: "common" }, // 1회
  { emoji: "🌈", id: "ico-131", rarity: "common" }, // 1회
  { emoji: "☮️", id: "ico-132", rarity: "common" }, // 1회
  { emoji: "🔴", id: "ico-133", rarity: "common" }, // 1회
  { emoji: "🪨", id: "ico-134", rarity: "common" }, // 1회
  { emoji: "🏃", id: "ico-135", rarity: "common" }, // 1회
  { emoji: "🧑", id: "ico-136", rarity: "common" }, // 1회
  { emoji: "💼", id: "ico-137", rarity: "common" }, // 1회
  { emoji: "🥀", id: "ico-138", rarity: "common" }, // 1회
  { emoji: "🪓", id: "ico-139", rarity: "common" }, // 1회
  { emoji: "🌳", id: "ico-140", rarity: "common" }, // 1회
  { emoji: "🌅", id: "ico-141", rarity: "common" }, // 1회
  { emoji: "📅", id: "ico-142", rarity: "common" }, // 1회
];

module.exports = { COMMON_EMOJI_ICONS };
