// Entry point — imports every section in original execution order.
import './utils.js';
import './data/900-pixelart-manifest.js';
import './data/001-block0-preamble.js';
import './misc/001-block0-preamble.js';
import './job/002-스킬-시스템.js';
import './items/003-골드-인벤토리-시스템.js';
import './items/004-장비-슬롯-시스템-12종.js';
import './data/006-세트-아이템-시스템.js';
import './items/006-세트-아이템-시스템.js';
import './data/007-동적-아이템-생성-시스템-무제한-영구-캐시.js';
import './items/007-동적-아이템-생성-시스템-무제한-영구-캐시.js';
import './data/008-클리어-보상-시스템-시나리오-클리어-시-영구-아이템스킬.js';
import './job/008-클리어-보상-시스템-시나리오-클리어-시-영구-아이템스킬.js';
import './data/009-레벨업-스탯-포인트-배분-시스템.js';
import './misc/009-레벨업-스탯-포인트-배분-시스템.js';
import './data/010-스킬-강화-시스템.js';
import './job/010-스킬-강화-시스템.js';
import './data/012-궁수-계열-T2-파생-5종-칭호-전사마법사도적-계열과-동일한-절제-원칙.js';
import './progression/012-궁수-계열-T2-파생-5종-칭호-전사마법사도적-계열과-동일한-절제-원칙.js';
import './race/013-종족-시스템.js';
import './data/014-환생-누적-시스템-110번.js';
import './progression/014-환생-누적-시스템-110번.js';
import './data/015-시스템-1120.js';
import './misc/015-시스템-1120.js';
import './data/016-2130번-시스템.js';
import './misc/016-2130번-시스템.js';
import './data/017-4150번-시스템.js';
import './misc/017-4150번-시스템.js';
import './data/018-5170번-환생-누적-시스템.js';
import './progression/018-5170번-환생-누적-시스템.js';
import './data/019-71100번-환생-누적-시스템.js';
import './progression/019-71100번-환생-누적-시스템.js';
import './data/020-101130번-환생-누적-시스템.js';
import './progression/020-101130번-환생-누적-시스템.js';
import './data/021-1-죽음의-메아리-시스템.js';
import './misc/021-1-죽음의-메아리-시스템.js';
import './misc/022-2-공허-감지-시스템.js';
import './data/023-3-균열-소환-시스템.js';
import './summon/023-3-균열-소환-시스템.js';
import './data/024-4-그림자-협약-시스템-다크링-핵심-협상-도구.js';
import './race/024-4-그림자-협약-시스템-다크링-핵심-협상-도구.js';
import './data/025-통합-패널-공허-확장-탭-시스템.js';
import './ui/025-통합-패널-공허-확장-탭-시스템.js';
import './data/026-renderHumanAwakeningPanel-완전-재정의.js';
import './ui/026-renderHumanAwakeningPanel-완전-재정의.js';
import './data/027-악마족-계약-장부-시스템-Demon-Contract-Ledger.js';
import './race/027-악마족-계약-장부-시스템-Demon-Contract-Ledger.js';
import './data/028-악마족-진명-시스템-Demon-True-Name.js';
import './race/028-악마족-진명-시스템-Demon-True-Name.js';
import './job/029-숨겨진-직업-시스템.js';
import './data/030-NEW-동적-클리어-목표-시스템.js';
import './misc/030-NEW-동적-클리어-목표-시스템.js';
import './data/031-NEW-NPC-성장-시스템-동료-레벨업-버프.js';
import './npc/031-NEW-NPC-성장-시스템-동료-레벨업-버프.js';
import './data/032-NEW-날씨계절-판정-연동-시스템.js';
import './world/032-NEW-날씨계절-판정-연동-시스템.js';
import './misc/033-NEW-배신-가능한-동료-시스템.js';
import './data/034-NEW-세계관별-고유-이벤트-테이블.js';
import './world/034-NEW-세계관별-고유-이벤트-테이블.js';
import './data/035-NEW-직업-조합-시너지-시스템.js';
import './job/035-NEW-직업-조합-시너지-시스템.js';
import './data/036-NEW-성장형-악당-시스템.js';
import './misc/036-NEW-성장형-악당-시스템.js';
import './progression/037-NEW-회차-연보-엔딩-히스토리-갤러리.js';
import './data/038-NEW-종족-전용-스토리-루트.js';
import './race/038-NEW-종족-전용-스토리-루트.js';
import './data/039-NEW-히든-퀘스트-시스템.js';
import './quest/039-NEW-히든-퀘스트-시스템.js';
import './data/041-궁수-계열-T2-파생-5종-히든-퀘스트-전사마법사도적-계열과-동일한-뼈대.js';
import './quest/041-궁수-계열-T2-파생-5종-히든-퀘스트-전사마법사도적-계열과-동일한-뼈대.js';
import './data/042-직업-시스템-무한-파생-도감.js';
import './job/042-직업-시스템-무한-파생-도감.js';
import './data/052-동대륙-추가-장소-4.js';
import './world/052-동대륙-추가-장소-4.js';
import './data/053-게시판-시스템.js';
import './misc/053-게시판-시스템.js';
import './data/054-이동수단-시스템.js';
import './misc/054-이동수단-시스템.js';
import './data/055-5대륙-왕국-시스템.js';
import './world/055-5대륙-왕국-시스템.js';
import './data/056-아멘호테프-남대륙-태양-신관-대신관-프로필-패치-v40.js';
import './world/056-아멘호테프-남대륙-태양-신관-대신관-프로필-패치-v40.js';
import './data/057-탈리스-동대륙-용골-연구소장-프로필-패치-v40.js';
import './world/057-탈리스-동대륙-용골-연구소장-프로필-패치-v40.js';
import './data/058-크리스탈리아-북대륙-룬-마법사-프로필-패치-v40.js';
import './items/058-크리스탈리아-북대륙-룬-마법사-프로필-패치-v40.js';
import './data/059-발타자르-해적왕-프로필-패치-v40.js';
import './misc/059-발타자르-해적왕-프로필-패치-v40.js';
import './data/060-마리넬라-폭풍-마법사-프로필-패치-v40.js';
import './misc/060-마리넬라-폭풍-마법사-프로필-패치-v40.js';
import './data/061-볼린-드워프-기계-사제-프로필-패치-v40.js';
import './religion/061-볼린-드워프-기계-사제-프로필-패치-v40.js';
import './data/062-봉인석-8개-각-대륙의-위치수호자전설현재-상태.js';
import './data/063-알테라-왕국-역대-왕-계보-1대-현재.js';
import './data/064-아에테른-종족간-전쟁-역사-종족-선택-시-배경.js';
import './race/064-아에테른-종족간-전쟁-역사-종족-선택-시-배경.js';
import './data/065-NPC퀘스트-완성도-강화.js';
import './items/065-NPC퀘스트-완성도-강화.js';
import './misc/066-②-선택-결과-추적-시스템.js';
import './npc/067-③-NPC-관계망-시스템.js';
import './data/068-전쟁-피해-플레이어-개입-시스템.js';
import './misc/068-전쟁-피해-플레이어-개입-시스템.js';
import './economy/069-④-경제-시스템.js';
import './world/070-⑤-세계-반응-시스템.js';
import './data/071-파트1-A-스킬-실제-발동-시스템.js';
import './job/071-파트1-A-스킬-실제-발동-시스템.js';
import './data/072-파트1-B-랜덤-이벤트-시스템.js';
import './misc/072-파트1-B-랜덤-이벤트-시스템.js';
import './world/073-파트2-A-날씨-게임플레이-반영.js';
import './items/074-파트2-B-성장-연출-강화.js';
import './data/075-파트2-C-크래프팅-시스템.js';
import './misc/075-파트2-C-크래프팅-시스템.js';
import './misc/076-파트2-D-일기기록-시스템.js';
import './ai-prompt/077-시스템-프롬프트-조립.js';
import './data/084-TaleForge-순수-JS-엔진.js';
import './core/084-TaleForge-순수-JS-엔진.js';
import './data/085-대륙-스타팅-시스템.js';
import './world/085-대륙-스타팅-시스템.js';
import './data/086-퀘스트임무-수락-팝업-시스템.js';
import './quest/086-퀘스트임무-수락-팝업-시스템.js';
import './data/087-전직-조건-저장로드-헬퍼-퀘스트아이템장소-등.js';
import './job/087-전직-조건-저장로드-헬퍼-퀘스트아이템장소-등.js';
import './data/088-업적-시스템-완전판-누적-보상-연결.js';
import './progression/088-업적-시스템-완전판-누적-보상-연결.js';
import './data/089-칭호-시스템-완전판-1개-활성화-스탯-효과-적용.js';
import './progression/089-칭호-시스템-완전판-1개-활성화-스탯-효과-적용.js';
import './data/090-1-마스터-데이터.js';
import './world/091-2-저장소.js';
import './religion/092-3-지역-종교-점유율-조회수정.js';
import './misc/093-4-긴장도-계산.js';
import './religion/094-5-플레이어-종교-귀속-교화.js';
import './combat/095-6-비전투-해결-경로-실행.js';
import './data/096-7-직업별-교화-가능-여부.js';
import './job/096-7-직업별-교화-가능-여부.js';
import './ui/097-8-패널-렌더.js';
import './ui/098-9-패널-탭-등록-renderPanel-훅.js';
import './religion/099-10-BLS-AI에게-종교-현황-전달.js';
import './ai-prompt/100-11-GS-처리-훅.js';
import './data/101-1-신앙fath-종교-시스템-실제-연동.js';
import './religion/101-1-신앙fath-종교-시스템-실제-연동.js';
import './data/102-2-종교-축복저주-판정-보너스.js';
import './religion/102-2-종교-축복저주-판정-보너스.js';
import './data/103-3-신의-응답-저주-시스템.js';
import './religion/103-3-신의-응답-저주-시스템.js';
import './religion/104-4-종교전쟁-결과-처리.js';
import './religion/105-5-제5-혼합-종파-Syncretism.js';
import './data/106-6-배교-페널티-시스템.js';
import './religion/106-6-배교-페널티-시스템.js';
import './data/107-7-성직자-비밀-퀘스트-라인.js';
import './quest/107-7-성직자-비밀-퀘스트-라인.js';
import './religion/108-8-이단-심문-시스템.js';
import './data/109-9-성지-시스템.js';
import './religion/109-9-성지-시스템.js';
import './religion/110-10-종교-시스템-매-턴-통합-훅.js';
import './religion/111-11-renderReligionPanel-보강-성지이단위험신앙등급비밀퀘스.js';
import './religion/112-12-BLS에-성지이단혼합종파-정보-추가.js';
import './religion/113-13-매-턴-종교-V2-훅-퀘스트체크전쟁진행성지타락이단.js';
import './religion/114-1-신규-종교-2개-추가.js';
import './data/115-2-창세신화-세계관-역사.js';
import './world/115-2-창세신화-세계관-역사.js';
import './data/116-3-만신전-신격-존재-정의.js';
import './religion/116-3-만신전-신격-존재-정의.js';
import './data/117-4-종교-전용-NPC-풀.js';
import './religion/117-4-종교-전용-NPC-풀.js';
import './data/118-5-종교-의례축제.js';
import './religion/118-5-종교-의례축제.js';
import './data/119-6-종교-사이드-퀘스트-20개-세계관-이해-연동.js';
import './religion/119-6-종교-사이드-퀘스트-20개-세계관-이해-연동.js';
import './religion/120-7-만신전-패널-신화-패널-렌더링.js';
import './religion/121-8-BLS에-만신전신화NPC-추가.js';
import './core/122-9-메뉴-버튼-openP-케이스-매-턴-연결.js';
import './core/123-0-저장키-통합-BLOODLINEKEY-하나로.js';
import './data/124-1-통합-혈통-정의-BLOODLINETYPES-BLOODLINEDEFS-.js';
import './summon/124-1-통합-혈통-정의-BLOODLINETYPES-BLOODLINEDEFS-.js';
import './job/125-4-자동-각성-감지-매-턴-AI-응답-텍스트-분석.js';
import './progression/126-5-회차-진화-완전-자동.js';
import './misc/127-6-BLOODLINETRAITS-캐릭터-생성-시-자동-적용.js';
import './items/128-7-회차-진화-시-자동-혈통-강화.js';
import './summon/129-8-GS-혈통-처리-bloodlineawaken-GS-자동-처리.js';
import './job/130-9-BLS-강화-회차-진화명-각성-상태-힌트-주입.js';
import './summon/131-10-혈통-패널-UI-완전히-자동-표시.js';
import './summon/132-11-환생-시-혈통-자동-처리.js';
import './summon/133-12-게임-시작-훅-자동-혈통-배정-연결.js';
import './core/134-13-매-턴-자동-체크-등록.js';
import './core/135-저장-키.js';
import './ai-prompt/136-GS-처리-clanjoin-clanleave-clanrepdelta-cl.js';
import './ai-prompt/137-BLS-가문-현황-AI-주입.js';
import './ui/138-UI-패널.js';
import './data/139-스토어-키.js';
import './npc/140-①-NPC-DB-가장-세분화.js';
import './quest/141-②-퀘스트-DB.js';
import './misc/142-③-사건-DB-태그-인덱스-전문-검색.js';
import './npc/143-④-관계-DB-NPC-간-관계망.js';
import './misc/144-⑤-플레이어-상태-DB.js';
import './world/145-⑥-세계-상태-DB.js';
import './npc/146-⑦-대화-DB-NPC별-실제-대화-전문-보존.js';
import './summon/147-⑧-소환수-상세-기억-DB.js';
import './ai-prompt/148-⑨-GS-DB-자동-파싱-모든-GS-필드-처리.js';
import './combat/150-전투-종료-후-포로-처리-UI.js';
import './items/151-⑩-자동-요약-압축-강화판.js';
import './ai-prompt/152-⑪-상황별-BLS-주입-Context-Aware.js';
import './ai-prompt/153-⑫-sendMsg-훅-자동-압축-GS-파싱-BLS-주입.js';
import './ui/154-⑬-buildLightSystem-최적화.js';
import './data/155-⑭-메모리-패널-UI.js';
import './ui/155-⑭-메모리-패널-UI.js';
import './data/156-NG-회차-계승-시스템.js';
import './progression/156-NG-회차-계승-시스템.js';
import './lore/157-예언-성취-추적-시스템.js';
import './npc/158-플레이어-평판-소문-시스템.js';
import './items/159-세트-아이템-효과-시스템-SETDEFS-calcSetBonus-로-통합됨.js';
import './data/160-환경-생존-시스템.js';
import './misc/160-환경-생존-시스템.js';
import './ai-prompt/161-컨텍스트-윈도우-모니터.js';
import './core/162-AI-응답-캐싱.js';
import './data/163-챕터막-구조-시스템.js';
import './misc/163-챕터막-구조-시스템.js';
import './data/164-도전-과제-달성률-시스템.js';
import './misc/164-도전-과제-달성률-시스템.js';
import './data/165-저장소.js';
import './world/165-저장소.js';
import './data/166-밸런스-상한선-과도한-누적-방지.js';
import './items/167-계승-아이템-획득.js';
import './progression/168-회차-종료-시-자동-계승-체크.js';
import './progression/169-계승-적용-새-회차-시작-시.js';
import './progression/170-계승-패널-UI.js';
import './core/171-DOM-주입.js';
import './ai-prompt/172-GS-처리-sendMsg-훅.js';
import './data/174-룬-정의-30종.js';
import './data/175-보석-정의-5종-5등급.js';
import './items/175-보석-정의-5종-5등급.js';
import './items/176-룬-새기기.js';
import './items/177-보석-박기.js';
import './data/178-인챈트-강화-시스템-1-15.js';
import './items/178-인챈트-강화-시스템-1-15.js';
import './items/179-총-룬보석-보너스-계산-적용.js';
import './items/180-룬-조합.js';
import './ui/181-UI-패널.js';
import './data/183-v49-⑥-onclick-연결됐지만-정의-없던-함수들.js';
import './patches/183-v49-⑥-onclick-연결됐지만-정의-없던-함수들.js';
import './patches/184-v49-⑧⑨⑩⑪-나머지-수정.js';
import './summon/186-1-소환수-loadSummons-saveSummons.js';
import './data/187-2-업적-시스템.js';
import './progression/187-2-업적-시스템.js';
import './data/188-UI-1-타임라인-전투로그-데이터-시스템.js';
import './combat/188-UI-1-타임라인-전투로그-데이터-시스템.js';
import './items/189-UI-2-스탯-패널-대폭-강화.js';
import './world/190-UI-3-세력-힘의-구도-시각화.js';
import './economy/191-UI-4-경제-현황-패널.js';
import './progression/192-UI-5-나비효과-패널.js';
import './ui/193-UI-6-패널-케이스-버튼-연결.js';
import './progression/194-NEW-1-명예의-전당-Hall-of-Fame.js';
import './job/195-NEW-2-스킬트리-시각화-UI-직업-계보-기반.js';
import './ui/196-NEW-3-속성-상성-심화-매트릭스-UI.js';
import './progression/197-NEW-4-나비효과-케이스-확장-4개-20개.js';
import './race/198-NEW-5-종족-공통-NPC-원한-시스템-강화.js';
import './world/199-NEW-6-세력-전쟁-영구-반영-시스템.js';
import './economy/200-NEW-7-경제-자동-변동-시스템.js';
import './ui/201-NEW-8-Carry-over-UI-패널.js';
import './progression/202-NEW-9-카르마-실제-판정-반영.js';
import './job/203-NEW-10-히든-직업-자동-감지-강화.js';
import './progression/205-패널-HTML-추가-명예의-전당-Carry-over-속성매트릭스.js';
import './data/206-3-진화Evolution-시스템.js';
import './misc/206-3-진화Evolution-시스템.js';
import './job/207-4-스킬-시스템.js';
import './data/208-5-직업-시스템.js';
import './job/208-5-직업-시스템.js';
import './quest/209-6-퀘스트-완료실패자동체크.js';
import './data/210-7-전투-시스템.js';
import './combat/210-7-전투-시스템.js';
import './data/211-8-로맨스-시스템.js';
import './npc/211-8-로맨스-시스템.js';
import './data/212-9-왕국-시스템.js';
import './world/212-9-왕국-시스템.js';
import './world/213-10-길드-시스템.js';
import './data/214-11-날씨-자동-순환.js';
import './world/214-11-날씨-자동-순환.js';
import './data/215-12-혈통-시스템.js';
import './summon/215-12-혈통-시스템.js';
import './data/216-13-운명-카드-시스템.js';
import './misc/216-13-운명-카드-시스템.js';
import './data/217-14-메모리-자동-요약.js';
import './misc/217-14-메모리-자동-요약.js';
import './data/218-15-인벤토리-addItem-removeItem.js';
import './items/218-15-인벤토리-addItem-removeItem.js';
import './data/219-17-세력-명성-변경-상태-조회.js';
import './world/219-17-세력-명성-변경-상태-조회.js';
import './data/220-18-회차루프-시스템.js';
import './progression/220-18-회차루프-시스템.js';
import './misc/221-19-탐험-discoverLocation-loadExploredLocat.js';
import './ai-prompt/222-21-processGSBlock-추가-필드-신규-시스템-연동.js';
import './patches/223-GS-규칙-추가-BUG2-FIX-blsExtraParts-방식으로-안전하.js';
import './patches/224-TaleForge-v51-2-누락-함수상수-전체-보완-패치-호환버전.js';
import './npc/226-①-NPC-관계도-시각화.js';
import './misc/227-②-복선미해결-떡밥-트래커.js';
import './misc/228-④-엔딩클리어-조건-시스템.js';
import './data/229-NPC-대화-퀘스트-시스템-AI-생성.js';
import './quest/229-NPC-대화-퀘스트-시스템-AI-생성.js';
import './data/230-방랑자-전용-혼돈질서-슬라이더-개연성P-시스템.js';
import './misc/230-방랑자-전용-혼돈질서-슬라이더-개연성P-시스템.js';
import './ui/231-스토리서사-캐릭터-성장-UIUX-개선-시스템.js';
import './ui/232-④-레벨업-전체화면-연출.js';
import './job/233-⑤-스킬-해금-드라마틱-연출.js';
import './ui/234-⑥-스탯-성장-미니-스파크라인-그래프-renderStats-보강.js';
import './misc/235-⑦-게임-현황-대시보드.js';
import './progression/236-①-칭호-획득-드라마틱-연출.js';
import './misc/237-③-메시지-버블-역할별-시각-개선.js';
import './data/238-④-로딩-애니메이션-개선-서사-생성-중-몰입감.js';
import './misc/238-④-로딩-애니메이션-개선-서사-생성-중-몰입감.js';
import './misc/239-⑤-서사-규칙-보강-선택지-결과-명확성-감정-일관성.js';
import './progression/240-⑥-칭호-패널-UI-개선-칭호-목록에-등급희귀도-표시.js';
import './ui/242-⑧-모바일-스와이프-제스처-좌우-패널-전환.js';
import './misc/243-⑩-상태이상-아이콘-헤더-직접-표시.js';
import './data/244-통합-초기화-매-턴-훅-연결.js';
import './core/244-통합-초기화-매-턴-훅-연결.js';
import './data/245-①-전투-지형-효과.js';
import './combat/245-①-전투-지형-효과.js';
import './data/246-②-적-AI-행동-패턴.js';
import './misc/246-②-적-AI-행동-패턴.js';
import './combat/247-③-부상-흔적-현재-전투-페널티-연결.js';
import './combat/248-④-기습선제-공격-시스템.js';
import './misc/249-⑤-적-사기Morale-시스템.js';
import './data/250-⑥-레어-전투-이벤트.js';
import './combat/250-⑥-레어-전투-이벤트.js';
import './data/251-통합-처리-함수-매-AI-응답-후-호출.js';
import './misc/251-통합-처리-함수-매-AI-응답-후-호출.js';
import './data/252-상단Caravan-UI-용병단-UI와-대칭-구조.js';
import './ui/252-상단Caravan-UI-용병단-UI와-대칭-구조.js';
import './data/253-SVG-타일-렌더링-작물-단계별-애니메이션.js';
import './misc/253-SVG-타일-렌더링-작물-단계별-애니메이션.js';
import './data/254-음유시인-공연-후원자-전설곡.js';
import './misc/254-음유시인-공연-후원자-전설곡.js';
import './data/255-상인-거래소-교역-지부-확장.js';
import './economy/255-상인-거래소-교역-지부-확장.js';
import './data/256-회차가-높을수록-보스가-더-빨리-더-강하게-스폰됨.js';
import './combat/256-회차가-높을수록-보스가-더-빨리-더-강하게-스폰됨.js';
import './data/257-renderMiniMap-던전-미니맵-일반-미니맵.js';
import './combat/257-renderMiniMap-던전-미니맵-일반-미니맵.js';
import './race/258-언데드-패널-렌더.js';
import './data/259-수인족-야생의-법칙-Law-of-the-Wild-시스템.js';
import './race/259-수인족-야생의-법칙-Law-of-the-Wild-시스템.js';
import './data/260-수인족-패널-렌더.js';
import './race/260-수인족-패널-렌더.js';
import './data/261-block4-preamble.js';
import './misc/261-block4-preamble.js';
import './data/263-저장소-키-6개-카테고리.js';
import './npc/264-NPC별-풍부한-데이터-구조.js';
import './quest/265-퀘스트별-풍부한-데이터-구조.js';
import './data/266-기본-구조.js';
import './core/267-저장로드초기화.js';
import './misc/268-현재-씬-분석-헬퍼.js';
import './npc/269-NPC-파트-업데이트.js';
import './quest/270-퀘스트-파트-업데이트.js';
import './world/271-세계관-파트-업데이트.js';
import './data/272-NPC-대화-학습-시스템-설계-문서-파일-최상단-주석-참조.js';
import './npc/272-NPC-대화-학습-시스템-설계-문서-파일-최상단-주석-참조.js';
import './world/273-영지-파트-업데이트.js';
import './lore/274-개인-기억-파트-업데이트.js';
import './misc/275-선택-파트-업데이트.js';
import './misc/277-PM-수동-편집-헬퍼-함수.js';
import './misc/278-메인-훅-연결.js';
import './misc/279-AUTO-PLAY-SYSTEM.js';
import './data/281-1-전투-시스템-실질화.js';
import './combat/281-1-전투-시스템-실질화.js';
import './items/282-2-인벤토리아이템-서사-연동.js';
import './ui/283-3-크래프팅-빠른-접근-UI.js';
import './data/284-4-동료-시스템-강화.js';
import './items/284-4-동료-시스템-강화.js';
import './data/285-5-경제-시스템-실질화.js';
import './economy/285-5-경제-시스템-실질화.js';
import './data/286-6-평판명성-통합-시스템.js';
import './npc/286-6-평판명성-통합-시스템.js';
import './data/287-7-선택-나비효과-강화.js';
import './items/287-7-선택-나비효과-강화.js';
import './items/288-8-레벨업성장-연출-강화.js';
import './data/289-9-세계-상태-변화-가시화.js';
import './world/289-9-세계-상태-변화-가시화.js';
import './data/290-10-진짜-미스터리-퀘스트라인.js';
import './quest/290-10-진짜-미스터리-퀘스트라인.js';
import './ui/291-통합-훅-sendMsg-buildLightSystem-패치.js';
import './data/292-block7-preamble.js';
import './misc/292-block7-preamble.js';
import './data/293-block8-preamble.js';
import './misc/293-block8-preamble.js';
import './npc/294-NPC-소문-계급별-정보-시스템.js';
import './ui/296-AI설정-패널-개발-콘솔eruda-토글.js';
import './patches/297-TaleForge-애니메이션-트리거-시스템-v57.js';
import './misc/298-훅-연결.js';
import './data/299-플레이-통계-성향-분석-시스템-v57-완전판.js';
import './patches/299-플레이-통계-성향-분석-시스템-v57-완전판.js';
import './lore/301-①-예언운명-시스템.js';
import './misc/302-②-꿈환영-시스템.js';
import './misc/303-③-자동-모험-연대기-Living-Chronicle.js';
import './world/304-④-세계-신화-백과사전.js';
import './npc/305-⑤-NPC-비밀-아젠다-이중성-시스템.js';
import './world/306-⑥-세계-시간-달력-시스템-확장.js';
import './misc/307-⑨-감정-분위기-시각-효과-시스템.js';
import './misc/308-sendMsg-후처리-통합-훅.js';
import './lore/309-게임-시작-시-예언-자동-생성-훅.js';
import './world/311-④-탐험-메모-지도-시스템.js';
import './lore/312-⑤-서약-시스템.js';
import './data/313-⑥-혈통-각성-시스템.js';
import './job/313-⑥-혈통-각성-시스템.js';
import './misc/314-⑤-이벤트-경매-시스템.js';
import './world/315-⑥-대륙-정치-지도.js';
import './lore/316-⑦-심층-트라우마-시스템.js';
import './misc/317-⑨-동맹배신-시스템.js';
import './misc/318-⑩-플레이어-목표-노트.js';
import './ai-prompt/319-BLS-통합-래퍼-새-시스템들-주입.js';
import './misc/320-MutationObserver-통합-기존-훅에-추가.js';
import './data/322-TaleForge-v58-매판-진득하게-살-수-있는-10가지-시스템.js';
import './patches/322-TaleForge-v58-매판-진득하게-살-수-있는-10가지-시스템.js';
import './misc/323-block13-preamble.js';
import './misc/324-block14-preamble.js';
import './misc/325-block15-preamble.js';
import './misc/326-block16-preamble.js';
import './misc/327-block17-preamble.js';
import './misc/328-block18-preamble.js';
import './misc/329-block19-preamble.js';
import './misc/330-block20-preamble.js';
import './quest/331-로컬-AI-모델-엔진.js';
import './economy/332-정착지-경제-평판-시스템.js';
import './world/320-⑦-실시간-필드-이동.js';

import { __tfDeferred_8 } from './job/010-스킬-강화-시스템.js';
import { __tfDeferred_17 } from './progression/020-101130번-환생-누적-시스템.js';
import { __tfDeferred_22 } from './ui/025-통합-패널-공허-확장-탭-시스템.js';
import { __tfDeferred_23 } from './ui/026-renderHumanAwakeningPanel-완전-재정의.js';
import { __tfDeferred_25 } from './race/028-악마족-진명-시스템-Demon-True-Name.js';
import { __tfDeferred_39 } from './world/052-동대륙-추가-장소-4.js';
import { __tfDeferred_40 } from './misc/053-게시판-시스템.js';
import { __tfDeferred_41 } from './misc/054-이동수단-시스템.js';
import { __tfDeferred_51 } from './race/064-아에테른-종족간-전쟁-역사-종족-선택-시-배경.js';
import { __tfDeferred_61 } from './items/074-파트2-B-성장-연출-강화.js';
import { __tfDeferred_63 } from './misc/076-파트2-D-일기기록-시스템.js';
import { __tfDeferred_65 } from './core/084-TaleForge-순수-JS-엔진.js';
import { __tfDeferred_67 } from './quest/086-퀘스트임무-수락-팝업-시스템.js';
import { __tfDeferred_68 } from './job/087-전직-조건-저장로드-헬퍼-퀘스트아이템장소-등.js';
import { __tfDeferred_70 } from './progression/089-칭호-시스템-완전판-1개-활성화-스탯-효과-적용.js';
import { __tfDeferred_75 } from './religion/094-5-플레이어-종교-귀속-교화.js';
import { __tfDeferred_76 } from './combat/095-6-비전투-해결-경로-실행.js';
import { __tfDeferred_78 } from './ui/097-8-패널-렌더.js';
import { __tfDeferred_80 } from './religion/099-10-BLS-AI에게-종교-현황-전달.js';
import { __tfDeferred_82 } from './religion/101-1-신앙fath-종교-시스템-실제-연동.js';
import { __tfDeferred_85 } from './religion/104-4-종교전쟁-결과-처리.js';
import { __tfDeferred_86 } from './religion/105-5-제5-혼합-종파-Syncretism.js';
import { __tfDeferred_87 } from './religion/106-6-배교-페널티-시스템.js';
import { __tfDeferred_92 } from './religion/111-11-renderReligionPanel-보강-성지이단위험신앙등급비밀퀘스.js';
import { __tfDeferred_93 } from './religion/112-12-BLS에-성지이단혼합종파-정보-추가.js';
import { __tfDeferred_94 } from './religion/113-13-매-턴-종교-V2-훅-퀘스트체크전쟁진행성지타락이단.js';
import { __tfDeferred_95 } from './religion/114-1-신규-종교-2개-추가.js';
import { __tfDeferred_102 } from './religion/121-8-BLS에-만신전신화NPC-추가.js';
import { __tfDeferred_103 } from './core/122-9-메뉴-버튼-openP-케이스-매-턴-연결.js';
import { __tfDeferred_111 } from './job/130-9-BLS-강화-회차-진화명-각성-상태-힌트-주입.js';
import { __tfDeferred_129 } from './ai-prompt/148-⑨-GS-DB-자동-파싱-모든-GS-필드-처리.js';
import { __tfDeferred_130 } from './combat/150-전투-종료-후-포로-처리-UI.js';
import { __tfDeferred_135 } from './ui/155-⑭-메모리-패널-UI.js';
import { __tfDeferred_161 } from './patches/183-v49-⑥-onclick-연결됐지만-정의-없던-함수들.js';
import { __tfDeferred_163 } from './summon/186-1-소환수-loadSummons-saveSummons.js';
import { __tfDeferred_166 } from './items/189-UI-2-스탯-패널-대폭-강화.js';
import { __tfDeferred_174 } from './progression/197-NEW-4-나비효과-케이스-확장-4개-20개.js';
import { __tfDeferred_198 } from './ai-prompt/222-21-processGSBlock-추가-필드-신규-시스템-연동.js';
import { __tfDeferred_200 } from './patches/224-TaleForge-v51-2-누락-함수상수-전체-보완-패치-호환버전.js';
import { __tfDeferred_203 } from './misc/228-④-엔딩클리어-조건-시스템.js';
import { __tfDeferred_204 } from './quest/229-NPC-대화-퀘스트-시스템-AI-생성.js';
import { __tfDeferred_205 } from './misc/230-방랑자-전용-혼돈질서-슬라이더-개연성P-시스템.js';
import { __tfDeferred_206 } from './ui/231-스토리서사-캐릭터-성장-UIUX-개선-시스템.js';
import { __tfDeferred_207 } from './ui/232-④-레벨업-전체화면-연출.js';
import { __tfDeferred_208 } from './job/233-⑤-스킬-해금-드라마틱-연출.js';
import { __tfDeferred_209 } from './ui/234-⑥-스탯-성장-미니-스파크라인-그래프-renderStats-보강.js';
import { __tfDeferred_211 } from './progression/236-①-칭호-획득-드라마틱-연출.js';
import { __tfDeferred_213 } from './misc/238-④-로딩-애니메이션-개선-서사-생성-중-몰입감.js';
import { __tfDeferred_214 } from './misc/239-⑤-서사-규칙-보강-선택지-결과-명확성-감정-일관성.js';
import { __tfDeferred_217 } from './misc/243-⑩-상태이상-아이콘-헤더-직접-표시.js';
import { __tfDeferred_218 } from './core/244-통합-초기화-매-턴-훅-연결.js';
import { __tfDeferred_219 } from './combat/245-①-전투-지형-효과.js';
import { __tfDeferred_225 } from './misc/251-통합-처리-함수-매-AI-응답-후-호출.js';
import { __tfDeferred_226 } from './ui/252-상단Caravan-UI-용병단-UI와-대칭-구조.js';
import { __tfDeferred_227 } from './misc/253-SVG-타일-렌더링-작물-단계별-애니메이션.js';
import { __tfDeferred_229 } from './economy/255-상인-거래소-교역-지부-확장.js';
import { __tfDeferred_230 } from './combat/256-회차가-높을수록-보스가-더-빨리-더-강하게-스폰됨.js';
import { __tfDeferred_231 } from './combat/257-renderMiniMap-던전-미니맵-일반-미니맵.js';
import { __tfDeferred_232 } from './race/258-언데드-패널-렌더.js';
import { __tfDeferred_233 } from './race/259-수인족-야생의-법칙-Law-of-the-Wild-시스템.js';
import { __tfDeferred_234 } from './race/260-수인족-패널-렌더.js';
import { __tfDeferred_259 } from './items/288-8-레벨업성장-연출-강화.js';
import { __tfDeferred_263 } from './misc/292-block7-preamble.js';
import { __tfDeferred_268 } from './misc/298-훅-연결.js';
import { __tfDeferred_269 } from './patches/299-플레이-통계-성향-분석-시스템-v57-완전판.js';
import { __tfDeferred_270 } from './lore/301-①-예언운명-시스템.js';
import { __tfDeferred_272 } from './misc/303-③-자동-모험-연대기-Living-Chronicle.js';
import { __tfDeferred_281 } from './job/313-⑥-혈통-각성-시스템.js';
import { __tfDeferred_294 } from './misc/327-block17-preamble.js';
import { __tfDeferred_295 } from './misc/328-block18-preamble.js';

// Run every deferred monkey-patch capture now that all 298 modules have
// finished their normal top-level evaluation, in original file order (see
// generate.js) -- NOT the order these functions happened to be defined in,
// which can differ (esbuild evaluates modules in dependency order).
[__tfDeferred_8, __tfDeferred_17, __tfDeferred_22, __tfDeferred_23, __tfDeferred_25, __tfDeferred_39, __tfDeferred_40, __tfDeferred_41, __tfDeferred_51, __tfDeferred_61, __tfDeferred_63, __tfDeferred_65, __tfDeferred_67, __tfDeferred_68, __tfDeferred_70, __tfDeferred_75, __tfDeferred_76, __tfDeferred_78, __tfDeferred_80, __tfDeferred_82, __tfDeferred_85, __tfDeferred_86, __tfDeferred_87, __tfDeferred_92, __tfDeferred_93, __tfDeferred_94, __tfDeferred_95, __tfDeferred_102, __tfDeferred_103, __tfDeferred_111, __tfDeferred_129, __tfDeferred_130, __tfDeferred_135, __tfDeferred_161, __tfDeferred_163, __tfDeferred_166, __tfDeferred_174, __tfDeferred_198, __tfDeferred_200, __tfDeferred_203, __tfDeferred_204, __tfDeferred_205, __tfDeferred_206, __tfDeferred_207, __tfDeferred_208, __tfDeferred_209, __tfDeferred_211, __tfDeferred_213, __tfDeferred_214, __tfDeferred_217, __tfDeferred_218, __tfDeferred_219, __tfDeferred_225, __tfDeferred_226, __tfDeferred_227, __tfDeferred_229, __tfDeferred_230, __tfDeferred_231, __tfDeferred_232, __tfDeferred_233, __tfDeferred_234, __tfDeferred_259, __tfDeferred_263, __tfDeferred_268, __tfDeferred_269, __tfDeferred_270, __tfDeferred_272, __tfDeferred_281, __tfDeferred_294, __tfDeferred_295].forEach(function(fn){ try { fn(); } catch(e) { console.error(e); } });
